#
# JDBC properties
#
spring.datasource.url=jdbc:mysql://employee-db.c5y6kc86ehkk.us-east-2.rds.amazonaws.com:3306/employee_directory
spring.datasource.username=springstudent
spring.datasource.password=springstudent


#mysql -h employee-db.c5y6kc86ehkk.us-east-2.rds.amazonaws.com -P 3306 -u springstudent -p'<Enter_DB_Password>' --ssl-verify-server-cert  --ssl-ca=/certs/global-bundle.pem mysql