name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '25'
      - name: Build Project
        run: mvn clean install -DskipTests
      - name: Deploy to EB
        uses: aws-actions/aws-elasticbeanstalk-deploy@v1.0.0
        with:
          aws-region: us-east-2
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: 'springboot-aws-deploy'
          environment_name: 'springboot-aws-deploy-env'
          version_label: ${{ github.sha }}
          region: us-east-2
          deployment_package: target/springboot-aws-deploy-1.0.0.jar
